#!/bin/bash

set -o pipefail

SCRIPT="`readlink -e $0`"
SCRIPTPATH="`dirname $SCRIPT`"

DIRARG="$1"

if [ "$DIRARG" = "" ] || [ ! -d "$DIRARG" ]; then
	echo $0: "Specify the directory of all player.dat files" >&2
	exit 1;
fi

if [ ! -f "$SCRIPTPATH/playerBasics2yaml" ]; then
	echo $0: Cannot find $SCRIPTPATH/playerBasics2yaml
	exit 1
fi

TEMPFILE=`tempfile -m 0644`

FILES=`find "$DIRARG" -type f -regex '.+/.+\.dat'`
FILES_COUNT=`echo "$FILES"| wc -w`

COUNT=0;
for i in $FILES; do
	COUNT=$(($COUNT+1));
	UUID="`echo -n $i|grep -Eo '[^/]+$'|cut -d '.' -f 1|sed 's/-//g'`";
	echo $UUID: >> $TEMPFILE
	"$SCRIPTPATH/playerBasics2yaml" "$i" | sed -E 's/^/  /' >> $TEMPFILE
	E=$?
	if [ $E -ne 0 ]; then
		echo $0: Non-zero exit status in piped commands >&2
		rm "$TEMPFILE"
		exit $E;
	fi
done

cat "$TEMPFILE"
rm "$TEMPFILE"
